import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import LoadingScreen from "@/components/loadingScreen";
import { LoaderProvider } from "@/components/loaderContext";
import { drukWide, twidGrotesk } from "@/fonts/fonts";
import "./globals.css";
import Navbar from "@/components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${drukWide.variable} ${twidGrotesk.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-black">
        <LoaderProvider >
          <LoadingScreen />
          {children}
        </LoaderProvider>
      </body>
    </html>
  );
}
